# Ruff = lint + import‑sort + some format
[tool.ruff]
line-length = 100
target-version = "py38"
show-fixes = true
# Ruff’s rule sets
extend-select = [
  "E",   # pycodestyle errors
  "F",   # pyflakes
  "I",   # isort
  "UP",  # pyupgrade
  "B",   # bugbear
  "A",   # built‑ins shadowing
  "S",   # bandit (security)
]
# Ignore SQLAlchemy’s dynamic attributes warnings
extend-ignore = ["B008"]  # (mutable default) example; extend as you wish
# Group & order imports like isort would
[tool.ruff.isort]
known-first-party = ["app", "tests"]
section-order = ["future", "standard-library", "third-party", "first-party", "localfolder"]

# Mypy (static typing) — optional but nice
[tool.mypy]
python_version = "3.8"
plugins = ["sqlalchemy.ext.mypy.plugin"]
strict = false
ignore_missing_imports = true
show_error_codes = true
pretty = true

# PyTest defaults
[tool.pytest.ini_options]
addopts = "-q -ra --cov=app --cov-report=term-missing"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]

# Coverage thresholds (fail CI if below)
[tool.coverage.run]
branch = true
source = ["app"]

[tool.coverage.report]
fail_under = 85
show_missing = true